# Generated by Django 3.1.6 on 2021-06-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0003_schedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='free_day_end_time',
            new_name='slot_end_time',
        ),
        migrations.RenameField(
            model_name='schedules',
            old_name='free_day_start_time',
            new_name='slot_start_time',
        ),
    ]
