# Generated by Django 3.1.6 on 2021-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0005_auto_20210601_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='slots',
            name='slot_start_time_integer',
            field=models.IntegerField(default=0),
        ),
    ]
