# Generated by Django 3.1.6 on 2021-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0006_auto_20210602_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='free_day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot_end_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot_start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
