# Generated by Django 3.1.6 on 2021-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0009_auto_20210604_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_admin',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
