# Generated by Django 3.1.6 on 2021-06-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0010_auto_20210604_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedAnswers', to='grad.question'),
        ),
    ]
