# Generated by Django 3.1.6 on 2021-06-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0011_auto_20210606_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='video_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedApp', to='grad.slots'),
        ),
    ]
